# Generated by Django 4.0.3 on 2022-03-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.IntegerField()),
                ('level_of_litter', models.CharField(choices=[('1', 'Not too bad'), ('2', 'Kind of gross'), ('3', 'This place needs some work'), ('4', 'Dear Lord please help'), ('5', 'Trashpocalypse')], default='1', max_length=100)),
            ],
        ),
    ]
