# Generated by Django 4.0.3 on 2022-03-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='zip_code',
            field=models.CharField(max_length=10),
        ),
    ]
