# Generated by Django 4.0 on 2022-03-12 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0003_zone_times_reported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='times_reported',
            field=models.IntegerField(default=0),
        ),
    ]
