# Generated by Django 4.0 on 2022-03-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0004_alter_zone_times_reported'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='city',
            field=models.CharField(default='New Jack City', max_length=256),
            preserve_default=False,
        ),
    ]
