# Generated by Django 4.0 on 2022-03-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0005_zone_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='reported_by',
            field=models.CharField(default='richardhendricks@piedpiper.com', max_length=256),
            preserve_default=False,
        ),
    ]
